#!/usr/bin/env python3

import re
from gradelib import *

r = Runner(save("xv6.out"))

@test(0, "pgtbltest")
def test_pgtbltest():
    r.run_qemu(shell_script([
        'pgtbltest'
    ]), timeout=300)

@test(10, "pgtbltest: print_kpgtbl", parent=test_pgtbltest)
def test_print_kpgtbl_():
    r.match(
        '^page table 0x',
        '^ \.\.0x0000000000000000',
        '^ \.\. \.\.0x0000000000000000',
        '^ \.\. \.\. \.\.0x0000000000000000',
        '^ \.\. \.\. \.\.0x0000000000001000',
        '^ \.\. \.\. \.\.0x0000000000002000',
        '^ \.\. \.\. \.\.0x0000000000003000',
        '^ \.\.(0xffffffffc0000000|0x0000003fc0000000)',
        '^ \.\. \.\.(0xffffffffffe00000|0x0000003fffe00000)',
        '^ \.\. \.\. \.\.(0xffffffffffffe000|0x0000003fffffe000)',
        '^ \.\. \.\. \.\.(0xfffffffffffff000|0x0000003ffffff000)',
    )

@test(30, "pgtbltest: superpg", parent=test_pgtbltest)
def test_superpg_():
    r.match('^superpg_test: OK$')

@test(0, "usertests")
def test_usertests():
    r.run_qemu(shell_script([
        'usertests -q'
    ]), timeout=300)

@test(10, "usertests: all tests", parent=test_usertests)
def test_usertests():
    r.match('^ALL TESTS PASSED$')

run_tests()
